ssbucarlos/smash-ultimate-blender

ultimate_exo_skel.py

Add Test MagicExoSkeleton functionality

---

operators/master_shader.py

Fixes invisiblity of shadeless materials

Shadeless Material Hotfix

---

operators/master_shader.py
panels/export_model.py
panels/import_model.py

Completes the .NUMATB export core functionality requirement

.NUMATB Export

---

operators/master_shader.py
panels/import_model.py

Shader Improvements

---

panels/export_model.py

Fix .NUMATB export

---

operators/master_shader.py
panels/export_model.py
panels/import_model.py

Adds CustomVector8, CustomVector47
Fixes colorset1 preview
Fixes emission-only material transparency
Now uses 'uvSet' for texture1

MoreShaderImprovements

---

panels/import_model.py

This greatly reduces loading times. The impact is larger for characters with more materials since the cost of the O(N) find operations adds up. The database is indexed, so SQLite can find the vertex attributes much faster. I've included a comment that links to how the file was generated. SQLite is very common and thankfully happens to be included with Blender.

Use SQLite database instead of JSON dump for nufx

---

panels/export_model.py
panels/import_model.py

fix export mesh w/o (parent bone & bone influence)

---

panels/export_model.py

fix broken colorset export

---

panels/export_model.py
panels/import_model.py

Preserve NUMSHB order

---

panels/export_model.py
panels/import_model.py

Fixed populated filename field #96

---

panels/export_model.py

I don't know if this is exactly what #92 wanted. It is automated, and, as a byproduct, it indirectly validates the model if it is triangulated.

Added automatic triangulation #92

---

__init__.py
panels/exo_skel.py
properties.py

Here's a quick [demo](https://youtu.be/IcEQCn5tmsA)
I added `bpy.ops.wm.save_mainfile()` to BuildBoneList, because it wouldn't build another bone list unless I saved (At least for me anyway).

Add UpdateBoneList

---

panels/export_model.py

I spent way too long trying to figure out how to do #104. I may not be doing this correctly, but this seemed to be the easiest solution. It may not be what you want in terms of how it is organized.

Added automatic split along UV seams #104

---

modules/exo_skel.py

Fixed exo skel being broken (forgot to update the helper bone property names in the exo skel maker)

Fixes #152

---

modules/export_anim.py

Default to true for ScaleOptions.inherit_scale

---

modules/export_anim.py

Ended up making misc animation optimzations to better conform to vanilla ultimate .nuanmb converntions

Misc. Animation Optimizations

---

modules/export_model.py

Also fixed exo skel export
Fixes #161

Dont add Helper bones in update.prc.

---

modules/export_model.py

Fix swing bone ordering on export

---

modules/export_anim.py

Set 'inherit_scale' to false when possible.

---

modules/export_model.py

Fixed the vert color POINT issues

---

__init__.py

Change to Semantic Versioning

---

__init__.py
modules/import_model.py
modules/material/create_blender_materials_from_matl.py
operators/master_shader.py
shader_nodes/custom_sampler_node.py
shader_nodes/custom_sprite_sheet_params_node.py
shader_nodes/custom_uv_transform_node.py
test/install_smush_blender_launch_blender.py

Now usable on 4.0.
Not Backwards Compatible, so version bumped to 1.0.0

Ssbucarlos/issue202 (4.0 Compatibility)

---

__init__.py
bpy_classes.py
modules/__init__.py
modules/updater/__init__.py
modules/updater/ui.py
modules/updater/version_check.py

Check for addon updates
